sonar.projectKey=tu-cv-spring-boot
sonar.projectName=TU-CV-Spring-Boot
sonar.projectVersion=1.0
sonar.sources=src/main
sonar.tests=src/test
sonar.java.source=11

# Disable S125 rule (commented-out code)
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S125
sonar.issue.ignore.multicriteria.e1.resourceKey=**